### ISSUE TITLE
`newdata="balanced"`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#105]

**Comment by vincentarelbundock** [comment]
@artiom-matvei 

This should be pretty easy. Change `sanitize_newdata()` to add "balanced" and then `datagrid(FUN_categorical= lambda x: np.uniquex))`

or something similar

**Comment by artiom-matvei** [comment]
we can close this issue since we merged: https://github.com/vincentarelbundock/pymarginaleffects/pull/122

**Comment by vincentarelbundock** [comment]
Thanks!
