### ISSUE TITLE
hypothesis and 0-indexing

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#109]
What do we currently do? Should we 0 index?

**Comment by vincentarelbundock** [comment]
@artiom-matvei In the `hypothesis` argument, we can compare two estimates like this:

```r
predictions(mod, hypothesis = "b0 - b1 = 0")
```

This would test if the difference between the predictions in row 0 and 1 of the data is different from zero.

In Python, we should use 0-indexing. This will be different behavior than in R, but consistent with indexing practices in Python.

I'm not sure what we do now. If we do 1-based indexing, it should be changed, along with tests, and a note about breaking change in the News.

**Comment by artiom-matvei** [comment]
We indeed use 1-based indexing
![image](https://github.com/user-attachments/assets/1223c151-7fe2-4b34-ae73-f0c54e4dadf4)
![image](https://github.com/user-attachments/assets/f50a7517-4c79-45dc-9d16-15a2bbc60259)
