### ISSUE TITLE
Round fivenum to 2 sigdig in plots

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#112]
When calling one of the `plot_*()` functions using a "threenum", "fivenum", or other shortcuts, we get several lines as expected. However, the labels for those lines get printed to a ridiculous precision, with lots of digits.

This feature request is to round the labels to 2 significant digits, for better display. 

Usage examples: https://marginaleffects.com/vignettes/plot.html#conditional-predictions

Relevant code to modify somewhere in `marginaleffects/plot_*.py` and `marginaleffects/p9.py`

```python
plot_predictions(
    mod,
    condition = {
        "flipper_length_mm": list(range(180, 221)),
        "bill_length_mm": "threenum",
        "species": dat["species"].unique(),
        }
)
```

Ideally, a pull request should also include one test, not with a visual snapshot (we avoid those unless really necessary), but with `draw=FALSE`, which should include appropriately rounded labels.

Note that, in `R`, labels get appropriately rounded. The output should look like:

**Comment by vincentarelbundock** [comment]
@artiom-matvei this is an old issue. Please confirm what is the current rounding policy for legends in plots. If we do not round, please round so that the legends are readable and numbers are displayed with two significant digits.

**Comment by artiom-matvei** [comment]
They are not rounded as per this test https://github.com/vincentarelbundock/pymarginaleffects/blob/main/tests/images/plot_slopes/issue114_slopes_03.png
and the code just executed
![image](https://github.com/user-attachments/assets/1484cabc-0cfe-4dd4-8407-6be71e015901)
```python
import polars as pl
import statsmodels.formula.api as smf
from marginaleffects import *
mtcars_df = pl.read_csv("tests/data/mtcars.csv")
mtcars_mod = smf.ols("mpg ~ hp * wt * disp * cyl * qsec", data=mtcars_df).fit()
plot_slopes(
            mtcars_mod, condition={"wt": None, "cyl": None, "disp": None, "qsec": None}, variables="hp",
)
```

**Comment by artiom-matvei** [comment]
hello @vincentarelbundock. we succesfully merged the branch aiming to solve this issue.
see this image test change
[tests/images/plot_slopes/issue114_slopes_03.png](https://github.com/vincentarelbundock/pymarginaleffects/pull/135/files#diff-bd1e7c8afbee4a48905ef050839c92998baf2533a6349bc0b96932239b2c6e8e)
Is there anything else needed to do in order to complete the issue?
