### ISSUE TITLE
Change np.Inf to np.inf

### ISSUE THREAD

**Issue by dafxy** [vincentarelbundock/pymarginaleffects#116]
Numpy 2.0 changed np.Inf to np.inf, so it is creating conflict in your package.

https://github.com/vincentarelbundock/pymarginaleffects/blob/2247728bb00035d89ef1f2646e5f5e438e7d2ab7/marginaleffects/uncertainty.py#L57

**Comment by vincentarelbundock** [comment]
Thanks for the note. Fixed on Github.
