### ISSUE TITLE
CSV files for local tests

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#123]
It would be nice to save a few CSV files locally so we can run the tests directly on them without having to be connected to the internet.

@artiom-matvei Do you think you could move the test infrastructure to use local files. Mostly, I think we'll need `mtcars`, `penguins`, `titanic`, and maybe a couple others should be enough.

**Comment by artiom-matvei** [comment]
Definitely yes, I already started doing something related by moving reusable models and dataframes to `conftest.py`

**Comment by artiom-matvei** [comment]
this also can be closed because of the merged pr: https://github.com/vincentarelbundock/pymarginaleffects/pull/122/files

**Comment by vincentarelbundock** [comment]
Thanks!
