### ISSUE TITLE
What is the documentation style used for the docstrings?

### ISSUE THREAD

**Issue by artiom-matvei** [vincentarelbundock/pymarginaleffects#127]
It seems like the documentation style used so far is similar to [numpydoc style:](https://numpydoc.readthedocs.io/en/latest/format.html)  
See [SO discussion ](https://stackoverflow.com/questions/3898572/what-are-the-most-common-python-docstring-formats)

**Comment by vincentarelbundock** [comment]
TBH, the documentation style is "whatever felt natural at the time". I agree that it is a good idea to pick one, but don't have a strong view on what is best.

Do you have a view on this?

If not, `Numpy` sounds appropriate since it is domain-relevant (data science, etc.)
