### ISSUE TITLE
predictions(., hypothesis) arguments inconsistency bw python and R

### ISSUE THREAD

**Issue by apoorvalal** [vincentarelbundock/pymarginaleffects#142]
The accompanying python replication code to the [JSS article](https://www.jstatsoft.org/article/view/v111i09) does not work at the following two lines 

```python
marg.predictions(m, by="democracy", hypothesis="b2 = b1 * 2")
marg.predictions(
    m, by="democracy", hypothesis="b2 = b1 * 2", equivalence=[-0.2, 0.2]
).select("term", "estimate", "std_error", "p_value_equiv")
```

with `NameError: name 'b2' is not defined`. 

A notebook demo-ing the correct python code either in the repo or the marginal effect zoo would be great.

**Comment by vincentarelbundock** [comment]
lol this is embarrassing.

Crazy week, but I'll look into it soon. Should be an easy fix.

Or maybe @artiom-matvei has time to take a look.

**Comment by vincentarelbundock** [comment]
Might be a b0 vs b1 issue. I think we decided it was necessary to make a breaking change so that Python used zero indexing.

**Comment by artiom-matvei** [comment]
@vincentarelbundock is there a way for me to update the replication code?

**Comment by pvsundar** [comment]
corrected code chunk
avg_predictions(m,
  by = "democracy",
  hypothesis = "pairwise")

predictions(m,
  by = "democracy",
  hypothesis = "b1 = b0 * 2")

predictions(m,
  by = "democracy",
  hypothesis = "b1 = b0 * 2",
  equivalence = [-.2, .2]) \
  .select("term", "estimate", "std_error", "p_value_equiv")

**Comment by vincentarelbundock** [comment]
Thanks everyone for confirming that the index of hypotheses in Python must start at `b0`. This is a type in the Python replication package.

I will collect a list of errors and typos found in the JSS here: https://github.com/vincentarelbundock/marginaleffects/issues/1293

After a while, I'll try to update the package at JSS, but I'm not sure if they will let me.
