### ISSUE TITLE
Support: pyfixest

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/pymarginaleffects#36]
https://github.com/s3alfisc/pyfixest

**Comment by vincentarelbundock** [comment]
```python
def is_object_of_type(obj, type_name): return type(obj).__name__ == type_name # Example usage: class MyClass: pass my_obj = MyClass() print(is_object_of_type(my_obj, "MyClass")) # Output: True print(is_object_of_type(my_obj, "AnotherClass")) # Output: False
```

**Comment by s3alfisc** [comment]
Hi @vincentarelbundock - let me know if I can do anything to support here! =)

**Comment by vincentarelbundock** [comment]
Thanks @s3alfisc, I really appreciate the offer!

Honestly, I'm not super familiar with the package. I've read the docs and the package looks really fantastic! I'm also a big fan of Laurent's work, so this is all very exciting for me. But I can't say I've played with the objects enough yet.

In principle, I think that all we'd need to do is to extend the functions in `getters.py` to support `pyfixest` models:

https://github.com/vincentarelbundock/pymarginaleffects/blob/main/marginaleffects/getters.py

There are only a few functions in there, and they're all very simple, so it should be very easy. Obviously, there might be other things to adjust after, but modifying those 5 functions should get us 98% of the way there.

I'll take a closer look when I can, but work is kind of crazy these days.

**Comment by vincentarelbundock** [comment]
@Nadjim10 Can you please modify the functions in the `getters.py` file to make sure they work with model objects produced by the `pyfixest` package? For example, `get_modeldata(mod)` should return a data frame with the original data regardless of wether `mod` is a `statsmodels` or a `pyfixest` object.

**Comment by Nadjim10** [comment]
@vincentarelbundock yes, no problem!

**Comment by s3alfisc** [comment]
Hi @Nadjim10 - I took a look at this the other day but did not get super far. But in case it helps you, here's how you can access everything you need from a fixest object: 

```py
from pyfixest.estimation import feols
from pyfixest.utils import get_data

data = get_data()
fit = feols("Y ~ X1", data = data)

fit._data #the data
fit._vcov # the variance covariance matrix
fit._coefnames # the names of the coefficients
fit._fml.split("~")[0] # the response variable 

fit.predict(newdata = data[0:100]) # prediction with newdata, works with and without fixed effects
```

When I played around with this, I was wondering if it might make sense to define an [abstract class with abstract methods ](https://www.geeksforgeeks.org/abstract-classes-in-python/)`get_modeldata()`, `find_response()` etc to fix an API & streamline the onboarding of new model classes? As an example from econometrics, I have sketched out an "abstract" difference-in-differences class [here](https://github.com/s3alfisc/pyfixest/blob/21d10a7235f1d2eb8ddd680e610cc0950aeec42e/pyfixest/experimental/did.py#L80).

**Comment by vincentarelbundock** [comment]
Thanks a lot for this @s3alfisc . Yes, I agree that using an abstract class would be a neat way to organize methods and blueprint future development.

**Comment by Nadjim10** [comment]
Thank you @s3alfisc and @vincentarelbundock ! I'll try this out!

**Comment by vincentarelbundock** [comment]
Since it looks like @Nadjim10 will not have time for this, I made an attempt here: https://github.com/vincentarelbundock/pymarginaleffects/pull/56

Closing this issue in favor of the PR.
